# Generated by Django 2.0.7 on 2018-08-07 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coache',
            name='course',
        ),
        migrations.AddField(
            model_name='coache',
            name='email',
            field=models.EmailField(default='admin@admin.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coache',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coache',
            name='role',
            field=models.CharField(choices=[('t', 'trener'), ('a', 'assistent')], default='t', max_length=20),
        ),
    ]
