# Generated by Django 2.0.7 on 2018-08-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180807_1627'),
        ('coaches', '0002_auto_20180807_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_colors', models.CharField(choices=[('r', 'red'), ('o', 'orange'), ('y', 'yellow)')], max_length=15)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Address')),
                ('dislike_courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
