# Generated by Django 2.0.7 on 2018-08-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coache',
            name='dossier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.Dossier'),
        ),
    ]
