# Generated by Django 2.0.7 on 2018-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_dossier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='dislike_courses',
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
