# Generated by Django 2.0.7 on 2018-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assistent',
            field=models.CharField(default='Zavrazina', max_length=50),
            preserve_default=False,
        ),
    ]
