# Generated by Django 2.0.7 on 2018-08-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180807_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_colors', models.CharField(choices=[('r', 'red'), ('o', 'orange'), ('y', 'yellow)')], max_length=15)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Address')),
                ('dislike_courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Address'),
        ),
    ]
